import Head from "next/head";
import Script from "next/script";
import dynamic from "next/dynamic";
import React, { useState, useEffect } from "react";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import gsap from "gsap";

import styles from "../styles/Home.module.scss";
import Viewport from "../components/Viewport";
import { start } from "repl";

export default function Home() {
	const [scrollY, setScrollY] = useState(0);

	function linearScrollY() {
		let y = window.scrollY == 0 ? 0 : window.scrollY / window.innerHeight;

		return 700 * y;
	}

	useEffect(() => {
		const handleScroll = () => {
			setScrollY(linearScrollY());
		};

		handleScroll();

		window.addEventListener("scroll", handleScroll);
		return () => {
			window.removeEventListener("scroll", handleScroll);
		};
	}, []);

	useEffect(() => {
		gsap.registerPlugin(ScrollTrigger);

		gsap.to(".viewport", {
			scrollTrigger: {
				trigger: "#trigger",
				start: "top 80%",
				end: "top 30%",
				scrub: true,
			},
			height: "50vh",
		});
	});

	return (
		<div className={`h-[400vh] w-full`}>
			<Head>
				<title>Visualize</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Viewport scroll={scrollY} />
			<div id="trigger" className="trigger top-[100vh] w-screen h-[300vh] absolute"></div>
		</div>
	);
}
