import Head from "next/head";
import Image from "next/image";
import { Canvas } from "@react-three/fiber";
import React, { useState, useEffect } from "react";

import styles from "../styles/Home.module.scss";
import Viewport from "../components/Viewport";

export default function Home() {
	const [scrollY, setScrollY] = useState(0);

	useEffect(() => {
		const handleScroll = () => {
			setScrollY(window.scrollY);
		};

		handleScroll();

		window.addEventListener("scroll", handleScroll);
		return () => {
			window.removeEventListener("scroll", handleScroll);
		};
	}, []);

	return (
		<div className={`h-[400vh] w-full`}>
			<Head>
				<title>Visualize</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Viewport scroll={scrollY} />
		</div>
	);
}